services:
  - type: web
    name: super-ai-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: API_KEY_FREE
        sync: false
      - key: API_KEY_PRO
        sync: false
      - key: API_KEY_BOSS
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_USERNAME
        sync: false
      - key: GITHUB_REPO
        sync: false
